<?php

########################################################################
# Extension Manager/Repository config file for ext: "typo3wiki"
#
# Auto generated by Extension Builder 2012-09-05
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TYPO3 Wiki',
	'description' => 'A modern wiki system for TYPO3 created with Extbase / Fluid',
	'category' => 'plugin',
	'author' => 'Bastian Bringenberg',
	'author_email' => 'typo3@bastian-bringenberg.de',
	'author_company' => 'Bastian Bringenberg',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.5',
			'fluid' => '1.5',
			'typo3' => '4.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>